let container2 = document.getElementsByClassName('container2')[0];
let btn = document.getElementById('btn');
btn.addEventListener('click', function() {
    container2.style.display = 'flex';
    let container = document.createElement('div');
    container.style.padding = '1em';
    container.style.boxShadow = '0px 0px 4px lightgrey';
    let form = document.createElement('form');
    let name = document.createElement('label');
    name.textContent = "Name: ";
    let nameInput = document.createElement('input');
    nameInput.type = 'text';
    let email = document.createElement('label');
    email.textContent = "Email: ";
    let emailInput = document.createElement('input');
    emailInput.type = 'email';
    form.style.flexDirection = 'column';
    form.style.display = 'flex';
    form.style.gap = '1em';
    let button = document.createElement('button');
    button.textContent = 'save';
    button.style.padding = '0.1em';
    button.style.fontSize = '1em';
    button.style.width = '5ch';
    button.style.alignSelf = 'center';
    button.type = 'button';
    name.appendChild(nameInput);
    email.appendChild(emailInput);
    form.appendChild(name);
    form.appendChild(email);
    form.appendChild(button);
    container.style.justifySelf = 'center';
    container.appendChild(form);
    container2.appendChild(container);
    button.addEventListener('click', function() {
        container2.style.justifyContent = 'space-around';
        let contactItem = document.createElement('div');
        let profile = document.createElement('div');
        profile.textContent = nameInput.value[0];
        container.style.display = 'none';
        contactItem.appendChild(profile);
        container2.appendChild(contactItem);
    });
});